export const environment = {
  production: false,
  local: true,
  API_ENVIRONMENT: 'local',
  STRIPE_LIFETIME_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_aEU8zJdFu6cofrq5ko',
  STRIPE_MONTHLY_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_5kAbLV1WM9oAcfe9AG',
  STRIPE_ANNUALLY_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_cN2dU358Y7gscfe5kp',
  FRONT_END_URL: 'http://localhost:4200',
  SUPABASE_URL: 'https://auth.kavindra.io',
  SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVucGVmeXNvdmV3Zm5hdmV1a2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk1NjY3NDUsImV4cCI6MjA0NTE0Mjc0NX0.cyRHfAwWrSTiUtR80FYHJ0eCPFJgPKz3FdNo4UdVKac',
  FLAGSMITH_CLIENT_SDK_KEY: '2eYv7n2m9yomhZkLFzRax5',
  FLAGSMITH_API_URL: 'https://flagsmith.production.releaseminder.io/api/v1/',
  PAYMENTS_SERVICE_BASE_URL: 'v1/payments',
  APPLICATION_MESSAGES_SERVICE_BASE_URL: 'v1/application-messages',
  USERS_SERVICE_BASE_URL: 'v1/users',
  NOTIFICATIONS_SERVICE_BASE_URL: 'v1/notifications',
};
